spring:
  config:
    activate:
      on-profile: docker
      
  kafka:
    bootstrap-servers: kafka:29092
    
  datasource:
    url: jdbc:mysql://mysql:3306/monitoring
    
  data:
    redis:
      host: redis
      port: 6379
