import { Activity, AlertTriangle, Bell, Gauge, LogOut, Menu, RadioTower, Send, Server, Shield } from 'lucide-react'
import { NavLink, Outlet } from 'react-router-dom'
import { useAuth } from 'react-oidc-context'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

const links = [{to:'/',label:'Overview',icon:Gauge},{to:'/anomalies',label:'Anomalies',icon:AlertTriangle},{to:'/services',label:'Services',icon:Server},{to:'/rules',label:'Alert rules',icon:Bell},{to:'/history',label:'Alert history',icon:Activity},{to:'/security',label:'Security',icon:Shield},{to:'/simulator',label:'Event simulator',icon:Send}]
export function AppShell() { const auth=useAuth(); const [open,setOpen]=useState(false); return <div className="min-h-screen"><aside className={cn('fixed inset-y-0 left-0 z-30 w-64 border-r bg-card p-4 transition-transform lg:translate-x-0', open?'translate-x-0':'-translate-x-full')}><div className="mb-8 flex items-center gap-3 px-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary text-primary-foreground"><RadioTower size={19}/></span><div><div className="font-semibold">Logsvar</div><div className="text-xs text-muted-foreground">AI monitoring</div></div></div><nav className="space-y-1">{links.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>cn('flex items-center gap-3 rounded-md px-3 py-2 text-sm transition-colors',isActive?'bg-primary/15 text-primary':'text-muted-foreground hover:bg-muted hover:text-foreground')}><Icon size={17}/>{label}</NavLink>)}</nav><div className="absolute bottom-4 left-4 right-4 border-t pt-4"><p className="mb-2 truncate px-2 text-xs text-muted-foreground">{auth.user?.profile.preferred_username || auth.user?.profile.email}</p><Button variant="ghost" className="w-full justify-start" onClick={()=>void auth.signoutRedirect()}><LogOut size={16}/>Sign out</Button></div></aside>{open&&<button aria-label="Close navigation" className="fixed inset-0 z-20 bg-black/60 lg:hidden" onClick={()=>setOpen(false)}/>}<div className="lg:pl-64"><header className="sticky top-0 z-10 flex h-16 items-center border-b bg-background/90 px-4 backdrop-blur lg:px-8"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></Button><div className="ml-auto flex items-center gap-2 text-xs text-muted-foreground"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Connected</div></header><main className="mx-auto max-w-7xl space-y-6 p-4 lg:p-8"><Outlet/></main></div></div> }
