ALTER TABLE alert_rules MODIFY id VARCHAR(36) NOT NULL;
ALTER TABLE alert_history MODIFY id VARCHAR(36) NOT NULL;
ALTER TABLE alert_history MODIFY anomaly_id VARCHAR(36) NOT NULL;
ALTER TABLE alert_history MODIFY rule_id VARCHAR(36) NOT NULL;
