apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: monitoring-app
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/monitoring"
  SPRING_DATASOURCE_USERNAME: "monitoring"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  REDIS_URL: "redis://redis:6379"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "monitoring"
  OLLAMA_URL: "http://ollama:11434"
  OLLAMA_MODEL: "gemma:7b"
