apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: monitoring-app
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "secret"
  MYSQL_ROOT_PASSWORD: "secret"
  MYSQL_PASSWORD: "secret"
  GATEWAY_INTERNAL_SECRET: "change-me-in-prod-min-32-chars"
  SMTP_HOST: ""
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_FROM: "alerts@monitoring.local"
  SLACK_WEBHOOK_URL: ""
  OAUTH2_JWK_SET_URI: ""
  OAUTH2_ISSUER_URI: ""
  OAUTH2_AUDIENCE: "monitoring-app"
