apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: monitoring
    user: root
    secureJsonData:
      password: secret
    editable: false
